on:
  rsshub:
    path: /bilibili/fav/${{ secrets.BILIBILI_ID }}/${{ secrets.BILIBILI_FAV_ID }}/disableEmbed
jobs:
  telegram:
    name: 发送 Telegram 消息
    runs-on: ubuntu-latest
    steps:
      - name: 提取图片链接
        uses: SettingDust/action-regex-match@main
        id: links
        with:
          text: ${{ on.rsshub.outputs.description }}
          regex: 'src="(.*?)"'
          flags: "gm"

      - name: 转义作者名
        uses: SettingDust/telegram-markdown-escape-action@main
        id: escape-author
        with:
          text: |
            ${{ on.rsshub.outputs.author }}
            ${{ on.rsshub.outputs.title }}

      - name: 下载图片
        uses: SettingDust/download-file-action@master
        id: download
        with:
          file-url: ${{ steps.links.outputs.matches }}

      - name: 压缩图片
        uses: SettingDust/image-compress-action@main
        id: compress
        with:
          files: ${{ steps.download.outputs.files }}
          min-size: 10485760
          max-dimension: 5000

      - name: 发送视频信息
        uses: SettingDust/telegram-action@main
        with:
          chatId: ${{ secrets.TELEGRAM_TO }}
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          content: |
            [${{ steps.escape-author.outputs.group1 }}](${{ on.rsshub.outputs.link }})
            作者：\#${{ steps.escape-author.outputs.group0 }}
            \#视频 \#bilibili
          medias: ${{ steps.compress.outputs.images }}
          type: photo
          disableWebPagePreview: true

      - uses: FedericoCarboni/setup-ffmpeg@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'

      - name: 安装 lux
        run: go install github.com/iawia002/lux@latest

      - name: 下载视频
        run: lux -o video -d -c $BILIBILI_COOKIE '${{ on.rsshub.outputs.link }}'
        env:
          BILIBILI_COOKIE: ${{ secrets.BILIBILI_COOKIE }}

      - name: 筛选视频文件
        uses: tj-actions/glob@v13
        id: glob
        with:
          files: |
            video/*.*
            !video/*.xml
          match-directories: false
          separator: \n

      - name: 归档视频
        uses: SettingDust/telegram-action@main
        with:
          chatId: ${{ secrets.TELEGRAM_ARCHIVE_TO }}
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          content: |
            [${{ steps.escape-author.outputs.group1 }}](${{ on.rsshub.outputs.link }})
            作者：\#${{ steps.escape-author.outputs.group0 }}
            \#视频 \#bilibili
          medias: |
            ${{ steps.download.outputs.files }}
            ${{ steps.glob.outputs.paths }}
          disableWebPagePreview: true
