on:
  rss:
    url: https://rsshub.app/pixiv/user/bookmarks/20119250
jobs:
  telegram:
    name: 发送 Telegram 消息
    runs-on: ubuntu-latest
    steps:
      - name: 提取图片链接
        uses: SettingDust/action-regex-match@main
        id: pics-links
        with:
          text: ${{ on.rss.outputs.content }}
          regex: 'src="(.*?)"'
          flags: 'gm'
      
      - name: 发送图片
        uses: SettingDust/telegram-action@main
        with:
          chatId: ${{ secrets.TELEGRAM_TO }}
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          content: |
            [${{ on.rss.outputs.title }}](${{ on.rss.outputs.link }}) ${{ on.rss.outputs.author }}
            #图片 #ACG
          photoUrls: ${{ steps.pics-links.outputs.matches }}
          disableWebPagePreview: true