on:
  rsshub:
    path: /pixiv/user/bookmarks/${{ secrets.PIXIV_ID }}
    rsshubConfig:
      PIXIV_REFRESHTOKEN: ${{ secrets.PIXIV_REFRESH_TOKEN }}
jobs:
  telegram:
    name: 发送 Telegram 消息
    runs-on: ubuntu-latest
    steps:
      - name: 提取图片链接
        uses: SettingDust/action-regex-match@main
        id: links
        with:
          text: ${{ on.rsshub.outputs.description }}
          regex: 'src="(.*?)"'
          flags: "gm"

      - name: 转义作者名
        uses: SettingDust/markdown-escape-action@main
        id: escape-author
        with:
          text: ${{ on.rsshub.outputs.author }}⭐${{ on.rsshub.outputs.title }}

      - name: 下载图片
        uses: SettingDust/download-file-action@master
        id: download
        with:
          file-url: ${{ steps.links.outputs.matches }}

      - name: 压缩图片
        uses: SettingDust/image-compress-action@main
        id: compress
        with:
          files: ${{ steps.download.outputs.files }}
          min-size: 10485760
          max-dimension: 5000

      - name: 发送图片
        uses: SettingDust/telegram-action@main
        with:
          chatId: ${{ secrets.TELEGRAM_TO }}
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          content: |
            [${{ steps.escape-author.outputs.1 }}](${{ on.rsshub.outputs.link }})
            作者：\#${{ steps.escape-author.outputs.0 }}
            \#图片 \#ACG
          photos: ${{ steps.compress.outputs.images }}
          disableWebPagePreview: true
