on:
  rss:
    url: https://rsshub.app/pixiv/user/bookmarks/20119250
    config:
      limit: 1
jobs:
  telegram:
    name: 发送 Telegram 消息
    runs-on: ubuntu-latest
    steps:
      - name: 提取图片链接
        uses: SettingDust/action-regex-match@main
        id: pics-links
        with:
          text: ${{ on.rss.outputs.content }}
          regex: 'src="(.*?)"'
          flags: 'gm'
      
      - name: 下载图片
        uses: SettingDust/download-file-action@master
        id: download-pics
        with:
          file-url: ${{ steps.pics-links.outputs.matches }}
          location: 'pics'

      - name: 测试
        run: 'echo ${{ steps.download-pics.outputs.file-path }}'